### ISSUE TITLE
Weird behaviour of 'suppress_graphite_events'

### ISSUE THREAD

**Issue by areina** [scottsuch/capistrano-graphite#26]
Hi,
This is something that I noticed some time ago, but I was talking about this today with @mikz. If I set `suppress_graphite_events` option to `true`, I would expect don't send an event to graphite. In fact, is how it is explained in Readme:
> Disable sending events for a particular stage by setting the following:
set :suppress_graphite_events, "true"

But, current implementation does exactly the opposite:
```ruby
if fetch(:suppress_graphite_events).downcase == 'true'
  GraphiteInterface.new.post_event("#{action}")
  info("#{action.capitalize} event posted to graphite.")
elsif fetch(:suppress_graphite_events).downcase == 'false'
  info('No event posted: `suppress_graphite_events` set to true.')
else
  warn('No event posted: `suppress_graphite_events` set incorrectly.')
end
```

What do you think @scottsuch ?

**Comment by scottsuch** [comment]
Weird, I thought I caught that a long time ago. Thanks for the catch. I can fix this sometime today, but don't have time right now. If you've got the time and want to submit a PR feel free. I'll cut the gem and upload a fixed version.

Thanks for the catch @areina and @mikz .
